<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%
    // Check if user is logged in
    model.User user = (model.User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect("../login.jsp?error=Unauthorized+access");
        return;
    }

    String role = user.getRole();
%>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>❓ Help - Pahana Edu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />

    <style>
        body {
            margin: 0;
            font-family: 'Segoe UI', sans-serif;
            background-color: #f8f9fa;
        }
        .main-content {
            margin-left: 240px;
            padding: 2rem;
        }
        .accordion-button:not(.collapsed) {
            background-color: #e0f2fe;
        }
    </style>
</head>
<body>

<%
    if ("admin".equals(role)) {
%>
    <%@ include file="../sidebars/admin_sidebar.jsp" %>
<%
    } else if ("cashier".equals(role)) {
%>
    <%@ include file="../sidebars/cashier_sidebar.jsp" %>
<%
    } else if ("storekeeper".equals(role)) {
%>
    <%@ include file="../sidebars/storekeeper_sidebar.jsp" %>
<%
    }
%>

<div class="main-content">
    <h2 class="mb-4">❓ Help & User Guide</h2>

    <div class="accordion" id="helpAccordion">

        <!-- Overview -->
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOverview">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOverview">
                    📘 System Overview
                </button>
            </h2>
            <div id="collapseOverview" class="accordion-collapse collapse show" data-bs-parent="#helpAccordion">
                <div class="accordion-body">
                    Pahana Edu is a web-based billing and inventory system used by the bookshop. It supports three roles:
                    <ul>
                        <li><strong>Admin</strong> – Full access to manage users, bills, and view analytics</li>
                        <li><strong>Cashier</strong> – Handles billing and customer-related tasks</li>
                        <li><strong>Store Keeper</strong> – Manages items and stock</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Admin Guide -->
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingAdmin">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAdmin">
                    🛡️ Admin Guide
                </button>
            </h2>
            <div id="collapseAdmin" class="accordion-collapse collapse" data-bs-parent="#helpAccordion">
                <div class="accordion-body">
                    <ul>
                        <li>➕ Add, Edit, and Delete users (Cashiers, Store Keepers)</li>
                        <li>📄 View all bills generated by cashiers</li>
                        <li>📇 Manage customer records</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Cashier Guide -->
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingCashier">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCashier">
                    💳 Cashier Guide
                </button>
            </h2>
            <div id="collapseCashier" class="accordion-collapse collapse" data-bs-parent="#helpAccordion">
                <div class="accordion-body">
                    <ul>
                        <li>🧾 Create bills for customers with selected items</li>
                        <li>📜 View bill history and individual bill details</li>
                        <li>📩 Email or download bill as PDF (new feature!)</li>
                        <li>👤 Manage customers (add/edit/delete)</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Store Keeper Guide -->
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingStore">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseStore">
                    📦 Store Keeper Guide
                </button>
            </h2>
            <div id="collapseStore" class="accordion-collapse collapse" data-bs-parent="#helpAccordion">
                <div class="accordion-body">
                    <ul>
                        <li>🗂️ Manage categories (add/edit/delete)</li>
                        <li>📋 Add and manage items in inventory</li>
                        <li>📈 Update item stock when new supplies arrive</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- FAQ -->
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingFAQ">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFAQ">
                    ❔ Frequently Asked Questions
                </button>
            </h2>
            <div id="collapseFAQ" class="accordion-collapse collapse" data-bs-parent="#helpAccordion">
                <div class="accordion-body">
                    <strong>Q: Can I change my password?</strong><br/>
                    A: Currently not via UI. Contact admin.<br/><br/>

                    <strong>Q: What happens when a bill is submitted?</strong><br/>
                    A: Items are saved, stock is updated, and a PDF/email option is shown.<br/><br/>

                    <strong>Q: How to fix "unauthorized access" errors?</strong><br/>
                    A: Login again or ensure you have correct role access.
                </div>
            </div>
        </div>

        <!-- Contact Support -->
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingSupport">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSupport">
                    ☎️ Contact Support
                </button>
            </h2>
            <div id="collapseSupport" class="accordion-collapse collapse" data-bs-parent="#helpAccordion">
                <div class="accordion-body">
                    If you encounter any issues, please contact the system administrator at:<br/>
                    <strong>Email:</strong> support@pahanaedu.lk<br/>
                    <strong>Phone:</strong> +94 77 123 4567
                </div>
            </div>
        </div>

    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<%@ include file="../common/footer.jsp" %>
</body>
</html>
